# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b3f3613acb127a078b9ec0fadaee40a1e98f5e5f15361228c4e4515d8c2621cd1c1a19bcb43e3ae21319b04427063c102a3f846f820f864cc013575ad2aa591

test:
  secret_key_base: 3e6aa687d42a192132d1400ba62c1f71ade3dd140642cffc5bddbe9ebd386352d3e27b0840890eae0b89d8cc58147fe7ce2bf87d91d2009220286bb9ea9a7f66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
